services:
  mysql:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: javatest
      MYSQL_USER: tester
      MYSQL_PASSWORD: password
    ports:
      - "5000:3306"
    networks:
      - microservices-net
    restart: unless-stopped

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    networks: 
      - microservices-net
    restart: unless-stopped	

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092, CONTROLLER://0.0.0.0:29093, EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092, EXTERNAL://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_NUM_PARTITIONS: 3
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPICS_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    networks: 
      - microservices-net
    restart: unless-stopped 
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - microservices-net
    restart: unless-stopped

  user-service:
    build:
      context: ./kafka-redis-test-user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: user-service
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/javatest
    - SPRING_DATASOURCE_USERNAME=tester
    - SPRING_DATASOURCE_PASSWORD=password
    - SPRING_DATA_REDIS_HOST=redis
    - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
    - mysql
    - redis
    - kafka
    networks:
    - microservices-net
    restart: on-failure

  email-service:
    build: 
      context: ./kafka-test-email-service
      dockerfile: Dockerfile
    ports:
    - "8083:8083"
    container_name: email-service
    environment:
    - SPRING_DATA_REDIS_HOST=redis
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/javatest
    - SPRING_DATASOURCE_USERNAME=tester
    - SPRING_DATASOURCE_PASSWORD=password
    - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    - SPRING_MAIL_HOST=mailhog
    - SPRING_MAIL_PORT=1025
    - USER_SERVICE_URL=http://user-service:8081
    - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
    - mysql
    - redis
    - kafka
    networks:
    - microservices-net
    restart: on-failure
networks:
  microservices-net:
    driver: bridge